# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LexBot' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LexBot
  pod 'JSQMessagesViewController', '~>7.3.4'
  pod 'AWSLex', '~>2.5.4'
end

